### ISSUE TITLE
Get the station type information

### ISSUE THREAD

**Issue by Desaydrone** [ChristopheCVB/EliteDangerousAPI#21]
Hi,

In Elite Dangerous, there are  6 station type, it could be usefull to add them to this plugin, so we can use this information tout show some nice icon

Hope that can be done easily

Cheers,

Tarlak

**Comment by ChristopheCVB** [comment]
Hi there!
Which event(s) are you talking about?

**Comment by CmdrIcke** [comment]
> Hi there!
> Which event(s) are you talking about?

Find in Docked, DockingGranted, DockingRequested, etc.  Docking*

**Comment by ChristopheCVB** [comment]
> > Hi there!
> > Which event(s) are you talking about?
> 
> Find in Docked, DockingGranted, DockingRequested, etc. Docking*

But it's there https://github.com/ChristopheCVB/EliteDangerousAPI/blob/200684fe8596305109d7bb753451c9b3868fbde7/src/main/java/com/christophecvb/elitedangerous/events/travel/DockedEvent.java#L11

**Comment by ChristopheCVB** [comment]
I'll just close this since I got no news from @Desaydrone
