### ISSUE TITLE
Adding a Listener

### ISSUE THREAD

**Issue by Timtower** [ChristopheCVB/EliteDangerousAPI#3]
With the previous API I could throw an instance of my class in the API as Listener, now I can't seem to do that.
Can you provide an example on that?

And maybe tell why you want to know which handler is using which event?

**Comment by ChristopheCVB** [comment]
Something like that:
```java
class ED implements Event.Listener {
  public static void main(String... args) {
    EliteDangerousAPI eliteDangerousAPI = new EliteDangerousAPI.Builder()
      .addEventListener(SupercruiseEntryEvent.class, this)
      .build();
    eliteDangerousAPI.start();
    //...
    eliteDangerousAPI.stop();
  }
  @Override
  public void onTriggered(Event event) {
    // Event triggered
    switch (event.getClass().getSimpleName()) {
      case "SupercruiseEntryEvent":
        // SupercruiseEntryEvent triggered
        break;
    }
  }
}
```
And to answer to "why you want to know which handler is using which event?", that is how I architectured the Listener part, it is way easier and flexible like that. What are you implying?

**Comment by Timtower** [comment]
I would personally not care about who is using what event.
Certainly not would want the user to do the same checks again that you already made before.

**Comment by ChristopheCVB** [comment]
I don't care about the who, but do care about the if. If there is no listener added by the developer, I don't want to call an empty method like it was before...
That is why you can use lambdas instead of your class implementing the Event.Listener like so:
```java
class ED {
  public static void main(String... args) {
    EliteDangerousAPI eliteDangerousAPI = new EliteDangerousAPI.Builder()
      .addEventListener(SupercruiseEntryEvent.class, event -> System.out.println(((SupercruiseEntryEvent) event).starSystem))
      .build();
    eliteDangerousAPI.start();
    //...
    eliteDangerousAPI.stop();
  }
}
```

**Comment by Timtower** [comment]
Extra cast and check though (if using multiple events on the same listener), more map access as well (not sure how bad that is though)
If I would use lambda's then I would just call a different function (after casting in this case)

**Comment by ChristopheCVB** [comment]
My original idea was to have a method signature for addEventListener like:
```java
public <T extends Event> Builder addEventListener(Class<T> eventClass, T.Listener listener)
```
I had in mind that T.Listener would force the developer to pass the right interface, but it just doesn't work as I had it in my head.
Also, keep in mind that the Library is still under heavy refactoring. I just hadn't the time to solve this tricky part and judged that it could remain like that for now. The v1.0.0 isn't released yet...
Finally, if you have a better method in mind, please explain it to me or make a pull request ;)

**Comment by Timtower** [comment]
I would personally revert to the many methods system. 
The public vars are probably just an effect of the refactor.

**Comment by ChristopheCVB** [comment]
No, because it is ugly as an API architecture. We can always discuss this in Discord if you want: Chris2A#3613
Yes.

**Comment by Timtower** [comment]
Considered doing something like this? 
[https://miro.medium.com/max/700/1*JsTvB7yiA51JpkwRLDjwRQ.png](url)

**Comment by ChristopheCVB** [comment]
I'm currently refactoring the Listeners part, it should allow you to do what you want

**Comment by ChristopheCVB** [comment]
Still not quite what I wanted but it's getting closer. I need to take the time to think this through.
Now you can do:
```java
class ED {
  public static void main(String... args) {
    EliteDangerousAPI eliteDangerousAPI = new EliteDangerousAPI.Builder()
      .addEventListener(MusicEvent.class, (MusicEvent.Listener) this::onMusic)
      .addEventListener(BountyEvent.class, (BountyEvent.Listener) bountyEvent -> System.out.println("onBountyEventTriggered " + bountyEvent))
      .build();
    eliteDangerousAPI.start();
    //...
    eliteDangerousAPI.stop();
  }

  private void onMusic(MusicEvent musicEvent) {
    System.out.println("onMusicEventTriggered " + musicEvent);
  }
}
```

**Comment by Timtower** [comment]
Didn't even know that Java could do that.
Currently in the process of switching to C# and JS though.
Software that I use is able to provide overlays / undocked windows, better than having it running next to the game.
