### ISSUE TITLE
states are not pulled if elite starts after touchportal

### ISSUE THREAD

**Issue by puuhbear** [ChristopheCVB/EliteDangerousAPI#51]
I need to restart touchportal in order to have the states shown correctly whenever I start (or restart) th elite dangerous client

**Comment by Pjiesco** [comment]
This is not an issue related to this project but a Touch Portal Plugin using this api.
You can report a bug about the plugin in the #elitedangerous channel in the [Touch Portal Discord server](https://discord.gg/MgxQb8r)
