### ISSUE TITLE
ScanPlanetOrMoonEvent misses systemAddress field

### ISSUE THREAD

**Issue by tastatortur** [ChristopheCVB/EliteDangerousAPI#54]
Hi there,
I think the ScanPlanetOrMoonEvent misses the systemAddress field (Long). It's included in the ScanStarEvent but I think it should be moved to the abstract ScanEvent. The event JSON provides it:

`
{ "timestamp":"2022-08-17T20:18:05Z", "event":"Scan", "ScanType":"Detailed", "BodyName":"LHS 2122 2", "BodyID":3, "Parents":[ {"Null":2}, {"Star":0} ], "StarSystem":"LHS 2122", "SystemAddress":7268561069481, "DistanceFromArrivalLS":564.383953, "TidalLock":true, "TerraformState":"", "PlanetClass":"Icy body", "Atmosphere":"", "AtmosphereType":"None", "Volcanism":"", "MassEM":0.142196, "Radius":4237765.000000, "SurfaceGravity":3.155900, "SurfaceTemperature":45.925526, "SurfacePressure":1.200703, "Landable":true, "Materials":[ { "Name":"sulphur", "Percent":22.654118 }, { "Name":"carbon", "Percent":19.049765 }, { "Name":"iron", "Percent":15.682040 }, { "Name":"phosphorus", "Percent":12.195987 }, { "Name":"nickel", "Percent":11.861238 }, { "Name":"chromium", "Percent":7.052734 }, { "Name":"manganese", "Percent":6.476522 }, { "Name":"zirconium", "Percent":1.821008 }, { "Name":"cadmium", "Percent":1.217781 }, { "Name":"tin", "Percent":1.020350 }, { "Name":"ruthenium", "Percent":0.968466 } ], "Composition":{ "Ice":0.676908, "Rock":0.217442, "Metal":0.105650 }, "SemiMajorAxis":109819138.050079, "Eccentricity":0.101043, "OrbitalInclination":-6.509743, "Periapsis":108.346898, "OrbitalPeriod":4451915.800571, "AscendingNode":179.527837, "MeanAnomaly":171.541899, "RotationPeriod":7909371.033029, "AxialTilt":-0.608184, "WasDiscovered":true, "WasMapped":true }`

See
https://github.com/SebastianSchlegel/EliteDangerousAPI/commit/037b54e6d00cee1a816f28861b1f6c7473958097
https://github.com/SebastianSchlegel/EliteDangerousAPI/commit/2ae65b298025b1b95c1970ea44334bc38172e102

I can open a pull request if you want.

Thanks for the good work with this API. I enjoy working with it!

BR
Sebastian

**Comment by tastatortur** [comment]
edited to clarify that the field is actually present in the ScanStarEvent but not in the abstract class

**Comment by ChristopheCVB** [comment]
Hi Sebastian! I'm glad you're enjoying the API. Please open the PR so I can review and merge it asap. I must have missed this in the documentation I used :/
Cheers!
Chris
